---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sftp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sftp
  valuesFrom:
    - kind: ConfigMap
      name: sftp-values
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: sftpgo
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: dashboard-crowdsec-web-ui
                labels:
                  sablier.enable: "true"
                  sablier.group: my-app-group