---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: sftp-credentials
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "d4177330-13aa-4f07-8d95-b42400fde970"
      secretKeyName: SFTPGO_DEFAULT_ADMIN_PASSWORD
    - bwSecretId: "613eef74-8adf-4f69-a14b-b3e6016f8c51"
      secretKeyName: SFTPGO_PLUGIN_AUTH_LDAP_PASSWORD
  authToken:
    secretName: bw-auth-token
    secretKey: token