---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample-trivy
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: trivy-operator-trivy-config
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "d9fa6dc0-2aa2-4e99-82f9-b485015db1d1"
      secretKeyName: GITHUB_TOKEN
    - bwSecretId: "614f4bb6-918c-4b1f-a364-b4a5016f8790"
      secretKeyName: TRIVY_TOKEN
    - bwSecretId: "67f9e730-451e-493a-80f5-b4a5016f9dd0"
      secretKeyName: TRIVY_USERNAME
    - bwSecretId: "d7c37838-319e-46c0-913f-b4a501700999"
      secretKeyName: TRIVY_PASSWORD
  authToken:
    secretName: bw-auth-token
    secretKey: token