---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample-tracearr
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: tracearr-credentials
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "d9fa6dc0-2aa2-4e99-82f9-b485015db1d1"
      secretKeyName: JWT_SECRET
    - bwSecretId: "9526b10a-65fa-473d-9d27-b485015dd5b5"
      secretKeyName: COOKIE_SECRET
    - bwSecretId: "858e3770-5545-4185-ba22-b485015f1bc0"
      secretKeyName: OIDC_CLIENT_SECRET
    - bwSecretId: "d2024fbf-8222-453c-b1fc-b4860107136a"
      secretKeyName: DB_PASSWORD
  authToken:
    secretName: bw-auth-token
    secretKey: token