---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  namespace: flux-system
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: cluster-config-secrets
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "1f7a25b9-72cf-491d-a522-b47301390ad8"
      secretKeyName: CLUSTER_DOMAIN
    - bwSecretId: "71f636e1-1358-4448-aac8-b47801575747"
      secretKeyName: LOADBALANCER_IP
    - bwSecretId: "853b361e-e15f-4ee6-b912-b4780162342a"
      secretKeyName: SMTP_HOST
    - bwSecretId: "dd7bbc3d-0660-4194-8810-b478016ad99d"
      secretKeyName: VAULT_SSO_CLIENT_SECRET_HASH
    - bwSecretId: "97c98962-373c-4625-a9a7-b478016058cf"
      secretKeyName: LINKEDIN_USER1_ID
    - bwSecretId: "6cf35a0d-0b4a-4d96-a919-b478016085d1"
      secretKeyName: PSEUDO_USER1_ID
    - bwSecretId: "fe2bfce1-2ba6-40fe-bc62-b4780154d7fc"
      secretKeyName: LDAP_USER1_EMAIL
    - bwSecretId: "273159c2-32ad-44d2-b543-b4780154fad2"
      secretKeyName: LDAP_USER1_FIRSTNAME
    - bwSecretId: "2604a982-8aa3-4348-be0c-b47801550c30"
      secretKeyName: LDAP_USER1_LASTNAME
    - bwSecretId: "b8bc5f9c-c9c2-4332-9042-b47801549b0a"
      secretKeyName: LDAP_USER1_ID
    - bwSecretId: "d56f0868-c780-4bde-9b3a-b47801556022"
      secretKeyName: LDAP_USER2_EMAIL
    - bwSecretId: "b3395645-414c-4e29-b21b-b478015574e2"
      secretKeyName: LDAP_USER2_FIRSTNAME
    - bwSecretId: "ae6c200d-948f-4d2f-a50c-b47801558a37"
      secretKeyName: LDAP_USER2_LASTNAME
    - bwSecretId: "ae1b8934-5188-4ce6-8bb1-b47801559df6"
      secretKeyName: LDAP_USER2_ID
    - bwSecretId: "01cc4f4e-1727-48f8-a777-b4780155b6fc"
      secretKeyName: LDAP_USER3_EMAIL
    - bwSecretId: "83bebe0b-f64f-447a-b629-b4780156274c"
      secretKeyName: LDAP_USER3_FIRSTNAME
    - bwSecretId: "1bb38948-87ea-478d-9e2c-b4780155e928"
      secretKeyName: LDAP_USER3_LASTNAME
    - bwSecretId: "00c051e2-7ec7-4e43-a430-b478015639f9"
      secretKeyName: LDAP_USER3_ID
    - bwSecretId: "307659c8-a37a-49ba-a764-b4780156aa3f"
      secretKeyName: LDAP_USER4_EMAIL
    - bwSecretId: "a6cf2d94-2c3a-458f-84de-b4780156d71c"
      secretKeyName: LDAP_USER4_FIRSTNAME
    - bwSecretId: "f5cf1353-1658-4b55-a372-b4780156c278"
      secretKeyName: LDAP_USER4_LASTNAME
    - bwSecretId: "eed003a3-da1e-48a7-8c27-b4780156f352"
      secretKeyName: LDAP_USER4_ID
    - bwSecretId: "84501a6c-48b1-4c27-946d-b479015e582b"
      secretKeyName: SEMAPHORE_SSO_SECRET
    - bwSecretId: "96b53b3e-f198-492e-a5e6-b479015e850c"
      secretKeyName: SEMAPHORE_SSO_CLIENT_SECRET_HASH
  authToken:
    secretName: bw-auth-token
    secretKey: token