#NAME            CHART VERSION   APP VERSION     DESCRIPTION                                  
#netdata/netdata 3.7.170         v2.10.4         Real-time performance monitoring, done right!
#! https://netdata.github.io/helmchart/