#! Use to interact with vaultwarden sqlite db 

apiVersion: v1
kind: Pod
metadata:
  name: sqlite-debug
  namespace: vault
  labels:
    app: sqlite-debug
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
  containers:
    - name: sqlite-debug
      image: keinos/sqlite3
      securityContext:
        runAsUser: 0
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: vault-vaultwarden
