apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-cm
data:
  hello.sh: |
    #!/bin/bash
    echo "Hello from Semaphore"
    date
    hostname
  restart_media_storage.yaml: |
    - hosts: all
      gather_facts: yes

      tasks:
        - command: k0s kubectl rollout restart deployment  servarr-jellyfin servarr-lidarr servarr-qbittorrent servarr-radarr servarr-sonarr
          register: result

        - debug:
            msg: "{{ result.stdout }}"