apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-cm
data:
  hello.sh: |
    #!/bin/bash
    echo "Hello from Semaphore"
    date
    hostname
  test.sh: |
    #!/bin/bash
    echo "Hello from Semaphore"
    date
    hostname
  hello.yaml: |
    - hosts: all
      gather_facts: yes

      tasks:
        - ping:

        - command: hostname
          register: result

        - debug:
            msg: "Connecté avec succès sur {{ result.stdout }}"

        - command: date
          register: date_result

        - debug:
            msg: "Date distante : {{ date_result.stdout }}"

        - debug:
            msg:
              - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
              - "Kernel: {{ ansible_kernel }}"
              - "Uptime host: {{ ansible_hostname }}"