apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: semaphore
resources:
  - namespace.yaml
  - repo.yaml
  - secret.yaml
  - cm.yaml
  - release.yaml
configMapGenerator:
  - name: semaphore-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true




# patches:
#   - target:
#       kind: Deployment
#       name: semaphore
#     patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: semaphore
#         labels:
#           sablier.enable: "true"
#       spec:
#         template:
#           metadata:
#             labels:
#               sablier.enable: "true"




# - op: add
#   path: /metadata/annotations
#   value:
#     sablier.group: "team-a,team-b"
#     sablier.running-hours: "09:00-18:00"
#     sablier.running-days: "Mon,Tue,Wed,Thu,Fri"
# - op: add
#   path: /spec/template/metadata/labels/sablier.enable
#   value: "true"