---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
spec:
  interval: 1h
  chart:
    spec:
      chart: semaphore
      version: '16.2.2'
      sourceRef:
        kind: HelmRepository
        name: semaphore
  valuesFrom:
    - kind: ConfigMap
      name: semaphore-values
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: semaphore
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: semaphore
                labels:
                  sablier.enable: "true"
                  sablier.group: semaphore

#  sablier.group: my-app-group