---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: secret-semaphore
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "0a264179-dc33-41ed-ac87-b4790160a44b"
      secretKeyName: cookieHash
    - bwSecretId: "b47d7183-3ce2-4b4b-bc91-b4790160bdf0"
      secretKeyName: cookieEncryption
    - bwSecretId: "596c0855-3b79-4d58-9cc3-b4790171d636"
      secretKeyName: username
    - bwSecretId: "d26a1137-0005-4267-a719-b4790171e967"
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token