apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubenav
resources:
  - namespace.yaml
  - repo.yaml
  - release.yaml
configMapGenerator:
  - name: kubenav-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true