---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: juicefs
spec:
  interval: 1h
  url: https://juicedata.github.io/charts/

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redis
spec:
  interval: 1h
  url: https://charts.pascaliske.dev