---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: juicefs-sc-secret
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "71f7d880-05cb-4501-8300-b44a0127c17d"
      secretKeyName: name
    - bwSecretId: "e3e7af3d-3fc9-4e6b-bb52-b4030124aa87"
      secretKeyName: metaurl
    - bwSecretId: "fa633365-2f85-4154-b9a9-b4030124bbeb"
      secretKeyName: storage
    - bwSecretId: "415601a3-1ee1-4af5-894f-b44a0127b1cf"
      secretKeyName: provider
    - bwSecretId: "66e6ede6-45ef-4e79-b85d-b44a0127a34a"
      secretKeyName: bucket
    - bwSecretId: "a0b2734b-780e-4e4e-9ac1-b44a0126ec54"
      secretKeyName: access-key
    - bwSecretId: "e267d250-3fc8-42b5-968b-b44a0126daa9"
      secretKeyName: secret-key
  authToken:
    secretName: bw-auth-token
    secretKey: token