---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: juicefs-sc-secret
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "a09d2d52-b7ee-481b-a06f-b403012481b8"
      secretKeyName: name
    - bwSecretId: "e3e7af3d-3fc9-4e6b-bb52-b4030124aa87"
      secretKeyName: metaurl
    - bwSecretId: "fa633365-2f85-4154-b9a9-b4030124bbeb"
      secretKeyName: storage
    - bwSecretId: "4b6f235e-4ec6-4766-8fed-b4030124cfe3"
      secretKeyName: provider
    - bwSecretId: "2091b2c1-957d-4c8f-be6e-b4030124e7fa"
      secretKeyName: bucket
    - bwSecretId: "a2f54dbc-1363-4ad0-8cb7-b40301250164"
      secretKeyName: access-key
    - bwSecretId: "b7415fb1-41ce-418b-9b7d-b40301251b7a"
      secretKeyName: secret-key
  authToken:
    secretName: bw-auth-token
    secretKey: token