apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  # namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: juicefs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-run
  # namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: linuxserver/nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: test-volume
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: web-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-run-service
  # namespace: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80