apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - repo.yaml
  - release.yaml
  # - secret.yaml
configMapGenerator:
  - name: flagger-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true