---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: wg-portal
  namespace: wg-portal
spec:
  interval: 5m0s
  url: oci://ghcr.io/h44z/charts/wg-portal
  ref:
    tag: 0.7.3