apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sm-operator-system
resources:
  - namespace.yaml
  - repo.yaml
  - release.yaml
  # - secret.yaml
configMapGenerator:
  - name: sm-operator-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true