---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sm-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: sm-operator
      version: '2.0.3'
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: sm-operator-system
  valuesFrom:
    - kind: ConfigMap
      name: sm-operator-values
      valuesKey: values.yaml
# '1.1.0'