#! example
# apiVersion: k8s.bitwarden.com/v1
# kind: BitwardenSecret
# metadata:
#   labels:
#     app.kubernetes.io/name: bitwardensecret
#     app.kubernetes.io/instance: bitwardensecret-sample
#     app.kubernetes.io/part-of: sm-operator
#     app.kubernetes.io/managed-by: kustomize
#     app.kubernetes.io/created-by: sm-operator
#   name: bitwardensecret-sample
# spec:
#   organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
#   secretName: bw-sample-secret
#   onlyMappedSecrets: true 
#   map:
#     - bwSecretId: 0c7be216-c69c-4bbf-83e7-b3dd0116ef14
#       secretKeyName: test
#   authToken:
#     secretName: bw-auth-token
#     secretKey: token