mode: standalone
type: postgresql

cluster:
  instances: 1
  enablePDB: false
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:15.18
  env: []

  initdb:
    database: immich
    owner: immich
    secret:
      name: "" 
      #immich-credentials # Name of the secret containing the initial credentials for the owner of the user database. If empty a new secret will be created from scratch
    options: []
    encoding: UTF8
    postInitSQL:
      - CREATE EXTENSION IF NOT EXISTS vector;

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  postgresql:
    shared_preload_libraries:
      - vchord.so

