---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wizarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: wizarr
  valuesFrom:
    - kind: ConfigMap
      name: wizarr-values
      valuesKey: values.yaml

# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: wizarr
#   namespace: media
# spec:
#   interval: 1h
#   chart:
#     spec:
#       chart: docker/helm/wizarr
#       sourceRef:
#         kind: GitRepository
#         name: wizarr
#         namespace: media

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: wizarr
# spec:
#   interval: 1h
#   chartRef:
#     kind: OCIRepository
#     name: wizarr
#   valuesFrom:
#     - kind: ConfigMap
#       name: wizarr-values
#       valuesKey: values.yaml
#   targetNamespace: media



# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmChart
# metadata:
#   name: podinfo
#   namespace: default
# spec:
#   interval: 5m0s
#   chart: podinfo
#   reconcileStrategy: ChartVersion
#   sourceRef:
#     kind: HelmRepository
#     name: podinfo
#   version: '5.*'

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: wizarr
# spec:
#   interval: 1h
#   chart:
#     spec:
#       chart: ./docker/helm/wizarr
#       sourceRef:
#         kind: GitRepository
#         name: wizarr
#         namespace: flux-system
#       reconcileStrategy: Revision
#   valuesFrom:
#     - kind: ConfigMap
#       name: wizarr-values
#       valuesKey: values.yaml
