---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: secret-authelia
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "613eef74-8adf-4f69-a14b-b3e6016f8c51"
      secretKeyName: authentication.ldap.password.txt
    - bwSecretId: "224268ce-afdf-4157-bb02-b3ee0159c96c"
      secretKeyName: identity_validation.reset_password.jwt.hmac.key
    - bwSecretId: "171667d3-0d9b-4b8b-ac1f-b3ee0159e2c4"
      secretKeyName: storage.encryption.key
    - bwSecretId: "6af67c5f-40c5-4e13-b315-b3ee0159f865"
      secretKeyName: session.encryption.key
    # - bwSecretId: "d096b71b-acd7-484a-99e5-b3ee015a063e"
    #   secretKeyName: notifier.smtp.password.txt
    - bwSecretId: "f4145c3c-65e1-4331-993e-b3ee015a1580"
      secretKeyName: identity_providers.oidc.hmac.key
    - bwSecretId: "ee3c739a-9de3-496a-9608-b3ee015a2858"
      secretKeyName: oidc.jwk.RS256.pem
  authToken:
    secretName: bw-auth-token
    secretKey: token