# apiVersion: source.toolkit.fluxcd.io/v1
# kind: GitRepository
# metadata:
#   name: tracearr
#   namespace: flux-system
# spec:
#   interval: 30m
#   url: https://github.com/connorgallopo/Tracearr
#   ref:
#     branch: main
# ---
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tracearr
  namespace: media
spec:
  interval: 1h
  url: oci://ghcr.io/connorgallopo/tracearr
  ref:
    tag: 4.12.4