# global:
#   # -- Set additional global labels
#   labels: {}
#   # -- Set additional global annotations
#   annotations: {}
#   # -- Set a global namespace
#   diagnosticMode:
#     enabled: false
#   fallbackDefaults:
#     # -- Define a storageClassName that will be used for all PVCs
#     # Can be overruled per PVC
#     storageClass: openebs-hostpath



# # -- Configure the ingresses for the chart here.
# # Additional ingresses can be added by adding a dictionary key similar to the 'main' ingress.
# # @default -- See below
# ingress:
#   main:
#     # -- Enables or disables the ingress
#     enabled: true
#     # -- Make this the primary ingress (used in probes, notes, etc...).
#     # If there is more than 1 ingress, make sure that only 1 ingress is marked as primary.
#     primary: true
#     # -- Ensure this ingress is always enabled.
#     required: false
#     # expandObjectName: false
#     # -- Provide additional labels which may be required.
#     labels: {}
#     # -- Provide additional annotations which may be required.
#     annotations: {}
#     # -- Set the ingressClass that is used for this ingress.
#     # Requires Kubernetes >=1.19
#     ingressClassName: "traefik"
#     # Defaults to primary service and primary port
#     # targetSelector:
#     #   # service: port
#     #   main: main
#     ## Configure the hosts for the ingress
#     hosts: 
#       - host: tracearr.${CLUSTER_DOMAIN}
#         # Change httpd.web_root in the sftpgo configuration if you change the path
#         paths:
#           - path: /
#             pathType: ImplementationSpecific
#     #   - # -- Host address. Helm template can be passed.
#     #     host: chart-example.local
#     #     ## Configure the paths for the host
#     #     paths:
#     #       - # -- Path.  Helm template can be passed.
#     #         path: /
#     #         # -- Ignored if not kubeVersion >= 1.14-0
#     #         pathType: Prefix
#     #         # -- Overrides the service reference for this path, by default the selector is honored
#     #         overrideService:
#     #           # -- Overrides the service name reference for this path
#     #           name:
#     #           # -- Overrides the service port reference for this path
#     #           port:
#     # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
#     # Gets ignored when clusterIssuer is filled
#     tls: []
#     #  - secretName: chart-example-tls
#     #    certificateIssuer: ""
#     #    hosts:
#     #      - chart-example.local
#     integrations:
#       certManager:
#         enabled: false
#         certificateIssuer: ""
#       traefik:
#         enabled: true
#         # Default to websecure
#         entrypoints:
#           - websecure
#         # Ensures tls annotation is set
#         forceTLS: true
#         middlewares: []
#         #   - name: my-middleware
#         #     # Optional, by default will try to
#         #     # "lookup" the namespace based on the name
#         #     namespace: ""
#       nginx:
#         enabled: false
#         themepark:
#           enabled: false
#           css: ""
#         ipWhitelist: []
#         auth:
#           # empty to disable, options: "authentik" or "authelia"
#           type: ""
#           # Internal Domain name + port to reach the auth provider, excluding http(s)
#           internalHost: ""
#           # External (ingress) Domain name to reach the auth provider, excluding http(s)
#           externalHost: ""
#           # Optional: override default response headers
#           responseHeaders: []
#       homepage:
#         enabled: true
#         # Default: chart name
#         name: "tracearr"
#         # Default: chart description
#         description: "Tracearr is a monitoring platform for Plex, Jellyfin, and Emby. "
#         # Default: no group
#         group: "Infrastructure"
#         # Default: chart icon
#         # icon: ""
#         # widget:
#         #   # Default: chartname
#         #   type: ""
#         #   # Default to ingress host 0
#         #   url: ""
#         #   custom:
#         #     # somesetting: some value
#         #   customkv:
#         #     # - key: some key
#         #     #   value: some value


# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/connorgallopo/tracearr
  pullPolicy: IfNotPresent
  tag: 2.2.3@sha256:d66822b5c5e76c27c12eec4de05c6eb9fbc4005968df5587bf5d2d3718f15dff

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 3000

cnpg:
  main:
    enabled: true
    user: tracearr
    database: tracearr
    # Database cluster configuration
    cluster:
      # Number of instances
      instances: 1
      # set to true on single-node clusters to allow PVCs to be kept on instance restart
      singleNode: true
redis:
  enabled: true
  redisUsername: default

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # JWT_SECRET: "changeme"
            # COOKIE_SECRET: "changeme"
            # Optional MaxMind GeoIP license key
            MAXMIND_LICENSE_KEY: ""
            CORS_ORIGIN: "*"
            LOG_LEVEL: debug
            # Enable reverse proxy support
            TRUST_PROXY: true
            OIDC_ISSUER_URL: https://auth.${CLUSTER_DOMAIN}
            OIDC_CLIENT_ID: tracearr
            OIDC_CLIENT_SECRET: ${TRACEARR_SSO_SECRET}
            GZIP_ENABLED: true
            OIDC_PROVIDER_NAME: Authelia 
            DATABASE_POOL_MAX: "50"
            POLLER_ENABLED: "true"
            POLLER_INTERVAL: "15000"
            MOBILE_BETA_MODE: "false"
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url