global:
  # -- Set additional global labels
  labels: {}
  # -- Set additional global annotations
  annotations: {}
  # -- Set a global namespace
  diagnosticMode:
    enabled: false
  fallbackDefaults:
    # -- Define a storageClassName that will be used for all PVCs
    # Can be overruled per PVC
    storageClass: openebs-hostpath
# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/connorgallopo/tracearr
  pullPolicy: IfNotPresent
  tag: 2.2.3@sha256:d66822b5c5e76c27c12eec4de05c6eb9fbc4005968df5587bf5d2d3718f15dff

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 3000

cnpg:
  main:
    enabled: true
    user: tracearr
    database: tracearr
    # Database cluster configuration
    cluster:
      # Number of instances
      instances: 1
      # set to true on single-node clusters to allow PVCs to be kept on instance restart
      singleNode: true
redis:
  enabled: true
  redisUsername: default

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # JWT_SECRET: "changeme"
            # COOKIE_SECRET: "changeme"
            # Optional MaxMind GeoIP license key
            MAXMIND_LICENSE_KEY: ""
            CORS_ORIGIN: "*"
            LOG_LEVEL: debug
            # Enable reverse proxy support
            TRUST_PROXY: true
            OIDC_ISSUER_URL: https://auth.${CLUSTER_DOMAIN}
            OIDC_CLIENT_ID: tracearr
            OIDC_CLIENT_SECRET: ${TRACEARR_SSO_SECRET}
            GZIP_ENABLED: true
            OIDC_PROVIDER_NAME: Authelia 
            DATABASE_POOL_MAX: "50"
            POLLER_ENABLED: "true"
            POLLER_INTERVAL: "15000"
            MOBILE_BETA_MODE: "false"
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url