# # # shelfmark.yaml
# # apiVersion: v1
# # kind: Namespace
# # metadata:
# # #   name: shelfmark
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: shelfmark-books
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelfmark
  namespace: media
  labels:
    app: shelfmark
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shelfmark
  template:
    metadata:
      labels:
        app: shelfmark
    spec:
      containers:
        - name: shelfmark
          image: ghcr.io/calibrain/shelfmark:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 8084
              name: http
          volumeMounts:
            - mountPath: /media
              name: media
              # subPath: downloads
            # - name: books
            #   mountPath: /books
            - name: config
              mountPath: /config
            # - name: downloads
            #   mountPath: /path/to/downloads
      volumes:
        - name: books
          persistentVolumeClaim:
            claimName: shelfmark-books
        - name: config
          persistentVolumeClaim:
            claimName: shelfmark-config
        - name: media
          persistentVolumeClaim:
            claimName: servarr-jellyfin-media
---
apiVersion: v1
kind: Service
metadata:
  name: shelfmark
  namespace: media
spec:
  selector:
    app: shelfmark
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shelfmark
  namespace: media
  annotations:
    gethomepage.dev/href: "https://book.${CLUSTER_DOMAIN}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Shelfmark is a self-hosted web interface for searching and requesting books and audiobooks across multiple sources."
    gethomepage.dev/group: Media
    gethomepage.dev/icon: "sh-shelfmark.png"
    gethomepage.dev/name: shelfmark
    gethomepage.dev/pod-selector: "app=shelfmark"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`book.${CLUSTER_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: 'chain-authelia-auth'
          namespace: 'authelia'
      services:
        - name: shelfmark
          port: 8084