---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: mattermost-secrets
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "3bbe3d91-950e-4fe7-a310-b4ae00fbcbd7"
      secretKeyName: mattermost-sso-client-secret
    - bwSecretId: "54783845-cfd8-4e6a-80bc-b4ae00fc27b1"
      secretKeyName: mattermost-db-datasource
    - bwSecretId: "76088a57-1f4a-4b57-9baa-b4ae00fc4c6e"
      secretKeyName: postgres-password
    - bwSecretId: "a382f007-a950-419a-b3bb-b4ae00fc7d14"
      secretKeyName: user-password
    - bwSecretId: "d6af8cbb-35aa-4688-a1d1-b3e6016fc155"
      secretKeyName: smtp-outgoing-password
  authToken:
    secretName: bw-auth-token
    secretKey: token
