apiVersion: v1
kind: Service
metadata:
  name: mattermost-calls
  namespace: mattermost
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    #app: mattermost
    app.kubernetes.io/name: mattermost
  ports:
    - name: calls-udp
      protocol: UDP
      port: 8443
      targetPort: 8443
      nodePort: 30443   
    - name: calls-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30443