# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: crowdsec-bouncer
#   namespace: traefik
# spec:
#   plugin:
#     crowdsec-bouncer:
#       enabled: true
#       crowdsecMode: stream
#       crowdsecLapiScheme: http
#       crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
#       crowdsecLapiKey: "${CROWDSEC_TRAEFIK_BOUNCER_KEY}"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer-appsec
  namespace: traefik
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiKey: "${CROWDSEC_TRAEFIK_BOUNCER_KEY}"
      crowdsecAppsecEnabled: true
      crowdsecAppsecHost: crowdsec-appsec-service.crowdsec.svc.cluster.local:7422
      crowdsecAppsecPath: /
      crowdsecAppsecFailureBlock: true
      crowdsecAppsecUnreachableBlock: true
      crowdsecAppsecBodyLimit: 10485760
      forwardedHeadersTrustedIPs: []
      clientTrustedIPs: []
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-lidarr
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: lidarr
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: Lidarr
        showDetails: true
        theme: ghost
        refreshFrequency: 15s

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-bazarr
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: bazarr
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: Bazarr
        showDetails: true
        theme: ghost
        refreshFrequency: 15s


---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-sftpgo
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: sftpgo
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: SFTP Server
        showDetails: true
        theme: ghost
        refreshFrequency: 15s

# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: sablier-mattermost
#   namespace: traefik
# spec:
#   plugin:
#     sablier:
#       sablierUrl: http://sablier-sablier:10000
#       group: mattermost
#       sessionDuration: 30m
#       keepAliveInterval: 5m
#       failOpen: true
#       ignoreUserAgent:
#         - curl
#         - "(?i)uptimerobot"
#       dynamic:
#         displayName: Mattermost & Mirotalk
#         showDetails: true
#         theme: ghost
#         refreshFrequency: 15s

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-crowdsec
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: crowdsec
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: Crowdsec dashboard
        showDetails: true
        theme: ghost
        refreshFrequency: 15s
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-semaphore
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: semaphore
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: Semaphore UI
        showDetails: true
        theme: ghost
        refreshFrequency: 15s

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-convertx
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: convertx
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: Convertx
        showDetails: true
        theme: ghost
        refreshFrequency: 15s


---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-stirling-pdf
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: stirling-pdf
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: Stirling-PDF
        showDetails: true
        theme: ghost
        refreshFrequency: 15s

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-metube
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: metube
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: MeTube
        showDetails: true
        theme: ghost
        refreshFrequency: 15s

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-seerr
  namespace: traefik
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier:10000
      group: seerr
      sessionDuration: 30m
      keepAliveInterval: 5m
      failOpen: true
      ignoreUserAgent:
        - curl
        - "(?i)uptimerobot"
      dynamic:
        displayName: seerr
        showDetails: true
        theme: ghost
        refreshFrequency: 15s


# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: botblocker
# spec:
#   plugin:
#     botblocker:
#       ipblocklisturls:
#         - "https://raw.githubusercontent.com/stamparm/ipsum/master/levels/5.txt"
#         - "https://lists.blocklist.de/lists/all.txt"
#       useragentblocklisturls:
#         - "https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_generator_lists/bad-user-agents.list"
# #---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: umami
#   namespace: traefik
# spec:
#   plugin:
#     umami: 
#       umamiHost: "http://umami.umami.svc.cluster.local:3000" 
#       umamiUsername: "admin"
#       umamiPassword: "umami" 
#       createNewWebsites: true
#       trackAllResources: true
#       ignoreIPs: []
#       headerIp: X-Forwarded-For
# ---
# apiVersion: traefik.io/v1alpha1 
# kind: Middleware
# metadata:
#   name: ip-whitelist
#   namespace: sliver
# spec:
#   ipAllowList:
#     sourceRange:
#       - "${LOADBALANCER_IP}/32"