---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '41.0.1'
      sourceRef:
        kind: HelmRepository
        name: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml
  # targetNamespace: longhorn
  # createTargetNamespace: true 
  # install:
  #   createNamespace: true
      # namespace: default

      # valuesFiles:
      #   - ./clusters/infrastructure/podinfo/values-env.yaml
        #- values-env.yaml
        #- values-env.yaml
  # values:
  #   replicaCount: 1
  #   resource:
  #     requests:
  #       cpu: 100m
  #       memory: 64Mi




# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmChart
# metadata:
#   name: podinfo
#   namespace: default
# spec:
#   interval: 5m0s
#   chart: podinfo
#   reconcileStrategy: ChartVersion
#   sourceRef:
#     kind: HelmRepository
#     name: podinfo
#   version: '5.*'