---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 1h
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.13.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich-db
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts