apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-umami-postgresql-0
  namespace: umami 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi 
  storageClassName: openebs-hostpath 