---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: vaultwarden-secrets
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: vaultwarden-secrets
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "d4116fe2-646e-45ed-b148-b3ee016d500c"
      secretKeyName: admin-token
    # - bwSecretId: "9f526ca3-11e8-40cc-bb7b-b3ee016d3224"
    #   secretKeyName: smtp-user
    # - bwSecretId: "7a7c8d30-0d4c-4962-828a-b3ee016d20b2"
    #   secretKeyName: smtp-password
    - bwSecretId: "e2762f39-deec-49e7-b02d-b3ee016842dd"
      secretKeyName: sso-client-secret
    - bwSecretId: "a5d23730-d13e-4473-81df-b3ee0171de39"
      secretKeyName: sso-authoriy
    - bwSecretId: "4327ac56-634f-428f-aa3c-b3ee01719764"
      secretKeyName: sso-client-id
  authToken:
    secretName: bw-auth-token
    secretKey: token