apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-jellyfin-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "juicefs-sc"
  resources:
    requests:
      storage: 1Ti