apiVersion: v1
kind: ServiceAccount
metadata:
  name: crowdsec-agent
  namespace: crowdsec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crowdsec-pods-log-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crowdsec-pods-log-reader-binding
subjects:
  - kind: ServiceAccount
    name: crowdsec-agent
    namespace: crowdsec
roleRef:
  kind: ClusterRole
  name: crowdsec-pods-log-reader
  apiGroup: rbac.authorization.k8s.io
