---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: crowdsec-lapi-secrets
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "8f4c51e7-eeb0-4a5e-846a-b48c017f1425"
      secretKeyName: csLapiSecret
    - bwSecretId: "c94a9c79-2a00-4f5f-ae93-b48c017f2d94"
      secretKeyName: registrationToken
    # - bwSecretId: "c09433c0-2c0b-40e1-8e0c-b48c01803f0f"
    #   secretKeyName: lapikey
    # - bwSecretId: "3cdcb7f2-862e-45e3-97cb-b48c01801dec"
    #   secretKeyName: lapiuser
  authToken:
    secretName: bw-auth-token
    secretKey: token
