---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: lldap-credentials
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "ec173a6e-b1c5-4601-9b98-b3e6016f406e"
      secretKeyName: jwtSecret
    - bwSecretId: "7593bb85-12e9-4272-91c2-b3e6016f6116"
      secretKeyName: keySeed
    - bwSecretId: "613eef74-8adf-4f69-a14b-b3e6016f8c51"
      secretKeyName: ldapUserPass
    - bwSecretId: "46c96534-d0b4-40d3-8c84-b3e6016ff058"
      secretKeyName: user1Password
    - bwSecretId: "0467f73a-1f0c-4918-b8da-b42200f6e249"
      secretKeyName: userpasswordtemp
    - bwSecretId: "b02d6891-494e-42d6-a8cb-b42200fa261c"
      secretKeyName: smtpPassword
  authToken:
    secretName: bw-auth-token
    secretKey: token