apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#? ORDER IMPORTANT
#! SECRETS
  - security/external-secrets
  - security/reflector
#* Apply secrets to load values
#! CSI
  - storage/local-storage
  - storage/juicefs
#! LB
  - app/traefik
#! MAIL
  - mail/maildev
#! SECURITY
  - security/ldap
  - security/authelia
  - security/authelia-admin
  - security/vaultwarden
  - security/wg-portal
  - security/crowdsec
  - security/falco
#! MONITORING
  # - monitoring/gatus
  - monitoring/dozzle
  - monitoring/vpa
  # - monitoring/maintenant
  - monitoring/kubenav
  - monitoring/ntfy
#! MEDIA
  - media/servarr
  - media/sftpgo
  - media/tracearr
  - media/shelfmark
  - media/vidbee
  # # - media/seerrng
  # - media/musicseerr
#! APPS
  # - app/gitea
  - app/homepage
  - app/semaphore
  # - app/sliver
  # - app/gowitness
  - app/adminer
  - app/immich