apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#? ORDER IMPORTANT
#! SECRETS
  - security/external-secrets
  - security/reflector
#* Apply secrets to load values
#! CSI
  - storage/local-storage
  - storage/juicefs
#! LB
  - app/traefik
#! MAIL
  - mail/maildev
#! SECURITY
  - security/ldap
  - security/authelia
  - security/vaultwarden
  - security/wg-portal
#! MONITORING
  - monitoring/gatus
  - monitoring/dozzle
# # #! ALERT
# #   - alert
#! MEDIA
  - media/servarr
  - media/sftpgo
  - media/streamystats
  - media/musicseerr
#! APPS
  - app/gitea
  - app/homepage
  - app/semaphore
  # - app/sliver