# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/thelounge/thelounge
  pullPolicy: IfNotPresent
  tag: 4.5.2@sha256:8aded5dfd825eb619d268292563c87f8ecd74c4e83a4f48cbcad82ffc6103466
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000

persistence:
  config:
    enabled: true
    mountPath: "/config"
    storageClass: openebs-hostpath
  configmap:
    enabled: true
    type: configmap
    objectName: thelounge-config
    expandObjectName: false
    optional: false
    # storageClass: openebs-hostpath
    defaultMode: "0777"
    mountPath: /config/config.js
    subPath: config.js

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"


# ingress:
#   ingressname:
#     enabled: true
#     integrations:
#       traefik:
#         enabled: true
#         entrypoints:
#           - websecure
#         routes:
#           - match: Host(`lounge.${CLUSTER_DOMAIN}`)
#             kind: Rule
#         forceTLS: true
#         middlewares:
#           - name: crowdsec-bouncer-appsec
#             namespace: "traefik"
#         services:
#           - name: thelounge
#             port: 10061
