---
kind: IngressRouteTCP
apiVersion: traefik.io/v1alpha1
metadata:
  name: gitea-ssh-ingress
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: gitea-ssh
      port: 22