---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "87ac8a11-cbc3-494d-9ac6-b3dd0111cc0d"
  secretName: gitea-ldap-secret
  onlyMappedSecrets: true 
  map:
    - bwSecretId: "613eef74-8adf-4f69-a14b-b3e6016f8c51"
      secretKeyName: bindPassword
    - bwSecretId: "9c7015b5-d153-4fdf-a649-b4190162e672"
      secretKeyName: bindDn
    - bwSecretId: "8b92aedc-b490-46f9-8c24-b44c0160ea49"
      secretKeyName: tokenRunner
    - bwSecretId: "ce5991de-7fd3-4dcb-953b-b44d010679c5"
      secretKeyName: password
    - bwSecretId: "798c1ca4-7b43-4aa2-994e-b44d0106585a"
      secretKeyName: username
  authToken:
    secretName: bw-auth-token
    secretKey: token