apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopiur-repo-data
  namespace: kopiur
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi