apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopiur-repo-data
  namespace: kopiur
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  #! Impossible with local 
    #- ReadWriteMany
  resources:
    requests:
      storage: 50Gi